package com.bancosantander.reglasnegociotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class inputPeriodoActual implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer montoAcumulado;
	private java.lang.Integer pagoTc;
	private java.util.Date fechaPago;
	private java.util.Date fechaLimitePago;

	public inputPeriodoActual() {
	}

	public java.lang.Integer getMontoAcumulado() {
		return this.montoAcumulado;
	}

	public void setMontoAcumulado(java.lang.Integer montoAcumulado) {
		this.montoAcumulado = montoAcumulado;
	}

	public java.lang.Integer getPagoTc() {
		return this.pagoTc;
	}

	public void setPagoTc(java.lang.Integer pagoTc) {
		this.pagoTc = pagoTc;
	}

	public java.util.Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(java.util.Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public java.util.Date getFechaLimitePago() {
		return this.fechaLimitePago;
	}

	public void setFechaLimitePago(java.util.Date fechaLimitePago) {
		this.fechaLimitePago = fechaLimitePago;
	}

	public inputPeriodoActual(java.lang.Integer montoAcumulado,
			java.lang.Integer pagoTc, java.util.Date fechaPago,
			java.util.Date fechaLimitePago) {
		this.montoAcumulado = montoAcumulado;
		this.pagoTc = pagoTc;
		this.fechaPago = fechaPago;
		this.fechaLimitePago = fechaLimitePago;
	}

}